zuul:
  routes:
      pets:
          path: /pets/**
          serviceId: vet.records
      owners:
          path: /owners/**
          serviceId: vet.owners

eureka:
  client:
      register-with-eureka: false
      service-url:
          default-zone: http://localhost:8761/eureka/
server:
  port: 6565