spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/p-ormeno/micro_examen_config
          repos:
            developper:
              pattern:
                - '*/dev'
              uri: https://github.com/p-ormeno/configDev
  application:
    name: config
             
#HTTP Server
server:
  port: 4444